AspNetDersleri/BootcampApp/Models/Bootcamp.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace BootcampApp.Models
{
    public class Bootcamp
    {
        public int Id { get; set; }
        public string? Title { get; set; }
        public string? Image { get; set; }
        public string? Description { get; set; }
        public string[]? Tags { get; set; }
        public bool isActive { get; set; }
        public bool isHome { get; set; }
    }
}

AspNetDersleri/BootcampApp/Models/ErrorViewModel.cs
namespace BootcampApp.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

AspNetDersleri/BootcampApp/Models/Repository.cs
namespace BootcampApp.Models{

    public class Repository{

        private static readonly List<Bootcamp> _bootcamp = new();

        static Repository(){

            _bootcamp = new List<Bootcamp>(){
            new Bootcamp(){Id = 1, Title="Full Stack Bootcamp",Image="1.jpg", Description="Html, css, jacaScrip ve asp net dersleri", Tags = new string[] {"html","css","aspnet core"}, isActive = true,isHome=true},
            new Bootcamp(){Id = 2, Title="Game Bootcamp",Image="2.jpg", Description="Unity ile mobil oyun geliştirme", Tags = new string[] {"unity","c#","mobil"}, isActive = true,isHome=true},
            new Bootcamp(){Id = 3, Title="SQL Bootcamp",Image="3.jpg", Description="Sql server kullanarak data da geliş.", Tags = new string[] {"sql server","tsql"}, isActive = false,isHome=true},
            new Bootcamp(){Id = 4, Title="Backend Bootcamp",Image="4.jpg", Description="Web geliştir arka planda", isActive = true,isHome=false}
            };
        }
        public static List<Bootcamp> Bootcamps{
            get{
                return _bootcamp;
            }
        }

        public static Bootcamp? GetById(int? id){
            return _bootcamp.FirstOrDefault(b => b.Id == id);
        }


    }
}

AspNetDersleri/BootcampApp/Controllers/BootcampController.cs
using BootcampApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace BootcampApp.Controllers;

public class BootcampController: Controller{

    public IActionResult Details(int? id){
        if(id==null){
            return Redirect("/Bootcamp/List");
        }
        var kurs = Repository.GetById(id);
        return View(kurs);
    }
    public IActionResult List(){      
        return View(Repository.Bootcamps);
    }


}

AspNetDersleri/BootcampApp/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using BootcampApp.Models;

namespace BootcampApp.Controllers;

public class HomeController : Controller
{
    public IActionResult Index()
    {        
        return View(Repository.Bootcamps);
    }
}

AspNetDersleri/BootcampApp/Views/Shared/_Abaout.cshtml
<div class="p-5 mb-4 bg-light -rounded-3">
    <div class="container-fluid py-5">
        <h1 class="display-5 fw-bold">About</h1>
        <p class="col-md-8 fs-4">Lorem ipsum dolor sit amet consectetur adipisicing elit. Perferendis et id, corporis odio ab, sed repellat dolorum eligendi expedita cupiditate quod necessitatibus unde debitis eos quas veritatis. Consectetur, sequi velit.</p>
        <button class="btn btn-danger btn-lg">Detay</button>

    </div>
</div>

AspNetDersleri/BootcampApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css">

    <title>Document</title>
</head>
<body>
     <header>
        @await Html.PartialAsync("_Navbar")
        @RenderSection("About", false)
    </header>
        <div class="container mt-3">
            <main>
            @RenderBody()
            </main>
        </div>
    
</body>

</html>

AspNetDersleri/BootcampApp/Views/Shared/_List.cshtml
@model Bootcamp
            <div class="card mb-3" id="kurs_@Model.Id">
                <div class="row">
                    <div class="col-md-3">
                        <img src="~/img/@Model.Image" class="img-fluid rounded-start" alt="My image" />
                    </div>
                    <div class="col-md-9">
                        <div class="card-body">
                        <h3>@Model.Title</h3>
                        <p>@Model.Description</p> 
                        </div>
                    </div>
                </div>
            </div>       

AspNetDersleri/BootcampApp/Views/Shared/_Navbar.cshtml
        <nav class="navbar navbar-expand-sm navbar-dark bg-danger">
            <div class="container">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">BootcampApp</a>
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Home" asp-action="Index" class="nav-link">Home</a>
                    </li>
                    <li class="nav-item">
                        <a asp-controller="Bootcamp" asp-action="List" class="nav-link">Bootcamp</a>
                    </li>
                </ul>
            </div>
        </nav>

  